version: '2'
services:
  web:
    build: .
    volumes:
      - ./log:/app/log # persist logs
      - ./public:/app/public
    depends_on:
      - db
    environment:
      RAILS_ENV: production
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD

  https-portal:
    image: steveltn/https-portal:1
    ports:
      - "80:80"
      - "443:443"
    volumes_from:
      - web
    depends_on:
      - web
    volumes:
        - ./containers/nginx/http_config:/var/lib/nginx-conf/localhost.conf.erb:ro
        - ./containers/nginx/https_config:/var/lib/nginx-conf/localhost.ssl.conf.erb:ro
    restart: always
    environment:
      DOMAINS: 'bigclout-api.kde.cs.tsukuba.ac.jp'
      STAGE: 'production'
      # FORCE_RENEW: true

  db:
    image: mysql:5.7
    volumes_from:
       - datastore
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --skip-character-set-client-handshake
    environment:
      - MYSQL_DATABASE=$DB_NAME
      - MYSQL_USER=$DB_USERNAME
      - MYSQL_PASSWORD=$DB_PASSWORD
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      - TZ="Asia/Tokyo"
    ports:
      - 3306:3306

  datastore:
     image: busybox
     volumes:
       - ./containers/db:/var/lib/mysql
